name: Trigger Pulumi Deployment
on:
  push:
    branches: [main]

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pulumi Deployment
        run: |
          curl -i -XPOST -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.PULUMI_ACCESS_TOKEN }}" \
            --location "https://api.pulumi.com/api/stacks/engineereddev/pr-stacker/main/deployments" \
            -d '{
              "operation": "update",
              "sourceContext": {
                "git": {
                  "repoURL": "https://github.com/EngineeredDev/pr-stacker-infra.git",
                  "branch": "main"
                }
              }
            }'
